### ISSUE TITLE
Audio (3.5mm Audio jack connection) not working in asus thinker board s

### ISSUE THREAD

**Issue by sradevski** [balena-os/balena-asus-tinker-board#29]
Reported by user, the device needs to be tested whether it is user-specific or the audio doesn't work.

**Comment by vicgal** [comment]
The following device needs to be selected for audio playback:
card 0: OnBoard [USB Audio OnBoard], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I did a test for the above device with `aplay` for a .wav file and with `mgp123` for a .mp3 file, and audio playback was successfull:
aplay -D plughw:0,2 sample.wav
mpg123 -a hw:0,2 sample.mp3
